### ISSUE TITLE
Unrecoverable crash when running `ord --index-sats index`

### ISSUE THREAD

**Issue by diwakergupta** [ordinals/ord#1884]
v0.5.1 on Mac M1.

`ord --index-sats index` ran for 2+ days, and then crashed with the following stack trace:

```
thread 'main' panicked at 'assertion failed: order <= self.get_max_order()', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/buddy_allocator.rs:367:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/page_manager.rs:1420:43
stack backtrace:
   0:        0x102d44880 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb33e6e8152f78c95
   1:        0x102d6194c - core::fmt::write::hd33da007f7a27e39
   2:        0x102d3e718 - std::io::Write::write_fmt::h7edc10723862001e
   3:        0x102d44694 - std::sys_common::backtrace::print::h895ee35b3f17b334
   4:        0x102d45e08 - std::panicking::default_hook::{{closure}}::h3b7ee083edc2ea3e
   5:        0x102d45b60 - std::panicking::default_hook::h4e7c2c28eba716f5
   6:        0x102d4642c - std::panicking::rust_panic_with_hook::h1672176227032c45
   7:        0x102d4624c - std::panicking::begin_panic_handler::{{closure}}::h0b2d072f9624d32e
   8:        0x102d44ce8 - std::sys_common::backtrace::__rust_end_short_backtrace::he9abda779115b93c
   9:        0x102d45fa8 - _rust_begin_unwind
  10:        0x102d90c24 - core::panicking::panic_fmt::h23ae44661fec0889
  11:        0x102d90f44 - core::result::unwrap_failed::h414a6cbb12b1e143
  12:        0x102bc6960 - <redb::tree_store::page_store::page_manager::TransactionalMemory as core::ops::drop::Drop>::drop::h762312e55308c9d8
  13:        0x102ba8a50 - core::ptr::drop_in_place<redb::tree_store::page_store::page_manager::TransactionalMemory>::h677a7932869004cf
  14:        0x102ba9db8 - redb::db::Database::new::hc5b941e691d0179b
  15:        0x10288cf50 - redb::db::Builder::open_mmapped::h2a97dcd929a747b3
  16:        0x10275d81c - ord::index::Index::open::h754eba78cc99d40a
  17:        0x1028a2918 - ord::subcommand::index::run::h4ceeabe72893775d
  18:        0x102700d68 - ord::subcommand::Subcommand::run::h53905ca6f0dacf3b
  19:        0x10285261c - ord::main::he7028d909b150bfb
  20:        0x1026601c8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h607000f7c2c37266
  21:        0x102660190 - std::rt::lang_start::{{closure}}::h276af28014218665
  22:        0x102d38a38 - std::rt::lang_start_internal::h00a235e820a7f01c
  23:        0x102660208 - _main
thread panicked while panicking. aborting.
```

Attempting to run `ord index` again crash instantly with the same trace.

Stack trace suggests a bug within `redb`.

**Comment by bensig** [comment]
Same error here on `Ubuntu 22.04.2 LTS` running `ord 0.5.1` 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/page_manager.rs:1420:43
```
