### ISSUE TITLE
testnet fails to sync with v0.11.0

### ISSUE THREAD

**Issue by ordinariusprof** [ordinals/ord#2646]
We have multiple versions of ord running and latest release v0.11.0 [commit](https://github.com/ordinals/ord/commit/084a370d8745acbbfa187ec3636a52acdc5ac402) failed to sync at testnet block height 2537558

UPDATE: restarting from scratch worked, ord synced ok on 2nd try. Leaving this up in case any one else comes across the issue.

> stderr: [2023-11-08T22:34:23Z INFO  ord::index] 2 block deep reorg detected at height 2537558
[2023-11-08T22:34:23Z INFO  ord::index::reorg] rolling back database after reorg of depth 2 at height 2537558
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/index/reorg.rs:66:76
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-11-08T22:34:23Z INFO  ord::index::updater] Block receiver disconnected: sending on a closed channel

Full backtrace
```
stderr: [2023-11-08T22:46:38Z INFO  ord::index] 2 block deep reorg detected at height 2537558
[2023-11-08T22:46:38Z INFO  ord::index::reorg] rolling back database after reorg of depth 2 at height 2537558
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/index/reorg.rs:66:
stderr: 76
stack backtrace:

stderr: [2023-11-08T22:46:38Z INFO  ord::index::updater] Block receiver disconnected: sending on a closed channel

stderr:    0:     0x563b2d28e6aa - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
              
stderr:                  at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563b2d28e6aa - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b2d28e6aa - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x563b2d28e6aa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22

stderr:    4:     0x563b2d2b982f - core::fmt::write::h9ffde816c577717b

stderr:                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x563b2d28a235 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:
stderr: 1698:15
   6:     0x563b2d28e475 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x563b2d28e475 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x
stderr: 563b2d28fc2e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22

stderr:    9:     0x563b2d28f9d5 - std
stderr: ::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x563b2d29018e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x563b2d290042 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7

stderr:                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
  12:     0x563b2d28eb16 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
        
stderr:                        at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x563b2d28fde2 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     
stderr: 0x563b2c890853 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:
stderr: 67:14
  15:     0x563b2c8908ed - core::panicking::panic::h0ead933cb8f56d66
       
stderr:                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5

stderr:   16:     0x563b2ca25ef3 - ord::index::reorg::Reorg::handle_reorg::h5e85321e4da64dd1
  17:     0x563b2c8e542c - 
stderr: ord::index::Index::update::hbda6d34b6bf6438f
  18:     0x563b2ccc6741 - ord::subcommand::index
stderr: ::update::run::h3baff21a57527875
  19:     0x563b2cbb66fc - ord
stderr: ::subcommand::Subcommand::run::h759dda4c3a4b2a89
  20:     0x563b2c904412 - ord
stderr: ::main::hfb7251ee5676ec5f
  21:     0x563b2c890fb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5d0006922d6bbc32
  22:     0x563b2c890fc9 - std::rt::lang_start::{{closure}}::h26edf04892f72125

stderr:   23:     
stderr: 0x563b2d2817ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
stderr: ::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  24:     0x563b2d2817ee - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  25:     0x563b2d2817ee - std::panicking::try::hd8a722c09d156a53
      
stderr:                          at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  26:     0x563b2d2817ee - std::panic::catch_unwind::hd2ca07971cf0119b
                 
stderr:               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  27:     0x563b2d2817ee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  28:     0x563b2d2817ee - std::panicking::try::do_call::hf47aa1aa005e5f1a
    
stderr:                            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  29:     0x563b2d2817ee - std::panicking::try::h73d246b2423eaf4e
   
stderr:                             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
 
stderr:  30:     0x563b2d2817ee - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  31:     0x563b2d2817ee - std::rt::lang_start_internal::h76f3e81e6b8f13f9
 
stderr:                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  32:     0x563b2c891025 - 
stderr: main

stderr:   33:     0x7f04c1ff8d0a - __libc_start_main
  34:    
stderr:  0x563b2c890eea - _start
  35:                0x0 - 
stderr: <unknown>

ord exited with code 101
```

**Comment by raphjaph** [comment]
Thanks, this is prob related to this #2363. Will look into it as soon as I have a bit more time

**Comment by ep150de** [comment]
I experienced this today trying to sync ord wallet balance.

**Comment by casey** [comment]
I think this is covered by #2363.

**Comment by casey** [comment]
I think this is covered by #2363.
