### ISSUE TITLE
Error while sending inscription

### ISSUE THREAD

**Issue by bitcointrumps** [ordinals/ord#3060]
While sending inscriptions this error occurred: 

ord --index /root/.local/share/ord/index.redb  --cookie-file /var/lib/bitcoind/.cookie wallet --name "NAME" send ADDRESS OUTGOING --fee-rate <FEE> --postage 8333sat

thread 'main' panicked at src/subcommand/wallet/transaction_builder.rs:566:13:
invariant: excess postage is stripped
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This seems to be a bug. Removing the postage option lets me send.

**Comment by raphjaph** [comment]
Which version of `ord`?

**Comment by bitcointrumps** [comment]
The current 15.0

**Comment by raphjaph** [comment]
Could you try running with a backtrace:

`RUST_BACKTRACE=1 ord --index /root/.local/share/ord/index.redb --cookie-file /var/lib/bitcoind/.cookie wallet --name "NAME" send ADDRESS OUTGOING --fee-rate --postage 8333sat`

And also see what happens if you change the postage a bit.

**Comment by LyricalString** [comment]
Hey @raphjaph . I just experienced this issue. My command looks like this:

RUST_BACKTRACE=1 ord wallet --name btc_ordi-assets send --postage 546sats --fee-rate 8 ADDRESS OUTGOING

My response was:

```
thread 'main' panicked at src/wallet/transaction_builder.rs:571:13:
invariant: excess postage is strippedstack backtrace:
   0: rust_begin_unwind             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: ord::wallet::transaction_builder::TransactionBuilder::build_transaction   3: ord::subcommand::wallet::send::Send::create_unsigned_send_satpoint_transaction
   4: ord::subcommand::wallet::send::Send::run   5: ord::subcommand::Subcommand::run
   6: ord::arguments::Arguments::run
   7: ord::main
```

**Comment by LyricalString** [comment]
My version of ord is 0.18.5

**Comment by raphjaph** [comment]
Could you try sending with a higher postage? Like 1000 sats and then let me know if that works.

**Comment by mvdnbrk** [comment]
I am having the same issue:

```
thread 'main' panicked at src/wallet/transaction_builder.rs:570:13:
invariant: excess postage is stripped
stack backtrace:
   0:        0x1034b4b30 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2260af3a60e707d0
   1:        0x1034d10e8 - core::fmt::write::h40c2acd4666eb4d3
   2:        0x1034c1340 - std::io::Write::write_fmt::h41d6e98dca6ecc3d
   3:        0x1034b49e4 - std::sys::backtrace::BacktraceLock::print::h6927682eb47cb165
   4:        0x1034a8e74 - std::panicking::default_hook::{{closure}}::h3800acb1d5aa9da8
   5:        0x1034a8d1c - std::panicking::default_hook::hdb07ba29d8151fe7
   6:        0x1034a9478 - std::panicking::rust_panic_with_hook::h3a42c361c08813d5
   7:        0x1034b5590 - std::panicking::begin_panic_handler::{{closure}}::h483101861bc4cead
   8:        0x1034b4d88 - std::sys::backtrace::__rust_end_short_backtrace::he99aa938f9475e2a
   9:        0x1034a8f04 - _rust_begin_unwind
  10:        0x10350c138 - core::panicking::panic_fmt::h5a90ea35d2c8d236
  11:        0x102ea68cc - ord::wallet::transaction_builder::TransactionBuilder::build_transaction::h4dbe4ac3baa11641
  12:        0x102eb0be4 - ord::wallet::Wallet::create_unsigned_send_satpoint_transaction::hc194233479a3263b
  13:        0x102b48d08 - ord::subcommand::wallet::send::Send::run::he5df2fac8e42ff1c
  14:        0x102e9b464 - ord::subcommand::wallet::WalletCommand::run::he6121ad82f72848b
  15:        0x102b4a1e8 - ord::subcommand::Subcommand::run::hae19b416f883be7a
  16:        0x102e8dbc4 - ord::arguments::Arguments::run::h2855229e4169616b
  17:        0x102cfa80c - ord::main::h23d950bb7e639eff
  18:        0x102a1d5a8 - std::sys::backtrace::__rust_begin_short_backtrace::h560d5a6b7f8bed7d
  19:        0x102a1d590 - std::rt::lang_start::{{closure}}::h05abec343067d3fe
  20:        0x1034a0df4 - std::rt::lang_start_internal::hadea728b8c40134b
  21:        0x102a1d604 - _main
```

**Comment by raphjaph** [comment]
Have you tried this?

> Could you try sending with a higher postage? Like 1000 sats and then let me know if that works.

**Comment by mvdnbrk** [comment]
Yeah sending with a higher postage works, I did  1000 instead of the initial postage of 546sats.
