### ISSUE TITLE
/r/blockinfo not working

### ISSUE THREAD

**Issue by ORDHeavens** [ordinals/ord#3143]
Dear all!

When I navigate to [ordinals.com/r/blockinfo/1](https://ordinals.com/r/blockinfo/1) it says page not found, am I spelling it correctly?

Best, DHeavens

**Comment by elocremarc** [comment]
@ORDHeavens that feature hasn't landed in a release yet.

**Comment by elocremarc** [comment]
@raphjaph trying this endpoint on regtest and its not responding giving this in the console.
```
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
```

**Comment by raphjaph** [comment]
I just ran this on `master` and with regtest and it works without problem.

Hash works:
```http://0.0.0.0/r/blockinfo/0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206```

Height works:
```http://0.0.0.0/r/blockinfo/0```

What command did you run exactly? (All flags and options)

if you did cargo run try a cargo clean before

**Comment by elocremarc** [comment]
I downloaded the pre-release binary ran that it worked!

However building from source

Started with clean then build

When going to /r/blockinfo/0 
```
eloc@XXXXX debug % ./ord -r server
Listening on http://0.0.0.0:80
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
thread 'tokio-runtime-worker' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/num/mod.rs:1190:5:
attempt to multiply with overflow
^CShutting down gracefully. Press <CTRL-C> again to shutdown immediately.
eloc@XXXX debug % git log  
commit f3df93f155ec8beedd427231b78f68ba0af5a454 (HEAD -> master, upstream/master, upstream/HEAD)
Author: bingryan <41174435+bingryan@users.noreply.github.com>
```

Tried cloning down ord fresh same issue.

**Comment by raphjaph** [comment]
Can you run with a BACKTRACE=1
