### ISSUE TITLE
ord env consistently panics at shutdown on Windows 

### ISSUE THREAD

**Issue by cryptoni9n** [ordinals/ord#3460]
going back to the first inclusion of the **`ord env`** command, I have never been able to get it to shutdown gracefully.  It always panics after a single CTRL-C.  In 0.17.1, I receive this message:

```
`ord` server URL:
http://127.0.0.1:9001
Example `bitcoin-cli` command:
bitcoin-cli -datadir=env getblockchaininfo
Example `ord` command:
C:\Users\nine\ord\target\release\ord.exe --datadir env wallet balance

Shutting down gracefully. Press <CTRL-C> again to shutdown immediately.
Shutting down gracefully. Press <CTRL-C> again to shutdown immediately.
thread 'main' panicked at src\subcommand\env.rs:10:8:
called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\subcommand\env.rs:10:8:
called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
stack backtrace:
   0:     0x7ff622a0cef2 - <unknown>
   1:     0x7ff622a3276d - <unknown>
   2:     0x7ff622a07611 - <unknown>
   3:     0x7ff622a0cd1a - <unknown>
   4:     0x7ff622a0f129 - <unknown>
   5:     0x7ff622a0ede5 - <unknown>
   6:     0x7ff622a0f644 - <unknown>
   7:     0x7ff622a0f519 - <unknown>
   8:     0x7ff622a0d7f9 - <unknown>
   9:     0x7ff622a0f1e6 - <unknown>
  10:     0x7ff622a868b7 - <unknown>
  11:     0x7ff622a86df3 - <unknown>
  12:     0x7ff6221f2f1a - <unknown>
  13:     0x7ff6221c17eb - <unknown>
  14:     0x7ff622207684 - <unknown>
  15:     0x7ffef5431030 - <unknown>
  16:     0x7ffef5434f5e - is_exception_typeof
  17:     0x7ffef543f500 - _C_specific_handler
  18:     0x7ffef543416c - is_exception_typeof
  19:     0x7ffef543fe41 - _CxxFrameHandler3
  20:     0x7fff175b449f - _chkstk
  21:     0x7fff1752fd54 - RtlUnwindEx
  22:     0x7ffef543f9ce - _C_specific_handler
  23:     0x7ffef5432e25 - is_exception_typeof
  24:     0x7ffef5433244 - is_exception_typeof
  25:     0x7ffef5434268 - is_exception_typeof
  26:     0x7ffef543fe41 - _CxxFrameHandler3
  27:     0x7fff175b441f - _chkstk
  28:     0x7fff1752e466 - RtlFindCharInUnicodeString
  29:     0x7fff17564475 - RtlRaiseException
  30:     0x7fff14dd5b0c - RaiseException
  31:     0x7ffef5436720 - CxxThrowException
  32:     0x7ff622a1ff1e - <unknown>
  33:     0x7ff622a0f999 - <unknown>
  34:     0x7ff622a0f6ad - <unknown>
  35:     0x7ff622a0f519 - <unknown>
  36:     0x7ff622a0d7f9 - <unknown>
  37:     0x7ff622a0f1e6 - <unknown>
  38:     0x7ff622a868b7 - <unknown>
  39:     0x7ff622a86df3 - <unknown>
  40:     0x7ff6221f2f1a - <unknown>
  41:     0x7ff6221c17eb - <unknown>
  42:     0x7ff622206175 - <unknown>
  43:     0x7ff6221e7af3 - <unknown>
  44:     0x7ff621d314a3 - <unknown>
  45:     0x7ff621ca1006 - <unknown>
  46:     0x7ff621ca101c - <unknown>
  47:     0x7ff6229fdf92 - <unknown>
  48:     0x7ff621ca107c - <unknown>
  49:     0x7ff622a5638c - <unknown>
  50:     0x7fff1674257d - BaseThreadInitThunk
  51:     0x7fff1756aa58 - RtlUserThreadStart
```

Please let me know if there is any further information I can provide to help with the fix.

**Comment by raphjaph** [comment]
Thanks for the report!

I think this might be related how we shutdown and send signals to the processes. Specifically how Windows handles SIGTERM differently
