### ISSUE TITLE
It is possible to create a wallet using ORD, but when entering the RECIVE command, an error message appears: thread 'main' panicked at src \ wallet \ wallet_constructor.rs:71:12:

### ISSUE THREAD

**Issue by qiangzhang111** [ordinals/ord#3593]
ord 0.18.0 Bitcore 27

**Comment by felipelincoln** [comment]
is your `ord-server` up? If so, are you also passing `--server-url` flag to the wallet command?
E.g.
```
ord wallet --server-url http://127.0.0.1:5000 receive
```

**Comment by qiangzhang111** [comment]
D:\Bitcoin1\ord>ord --cookie-file D:\Bitcoin1\.cookie wallet receive
thread 'main' panicked at src\wallet\wallet_constructor.rs:71:12:
wallet failed to talk to server. Make sure `ord server` is running.: ParseIntError { kind: Empty }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

D:\Bitcoin1\ord>ord --cookie-file D:\Bitcoin1\.cookie wallet --server-url http://127.0.0.1:5000 receive
thread 'main' panicked at src\wallet\wallet_constructor.rs:71:12:
wallet failed to talk to server. Make sure `ord server` is running.: ParseIntError { kind: Empty }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The same error occurred. I tried to delete the wallet and restart it, but still received the same error message

**Comment by felipelincoln** [comment]
You should use the port that your ord server is running at.
`5000` was an example, it is what I use, I guess the default is `80`.

**Comment by xinzhongyouhai** [comment]
> 进行更改后，仍然出现相同的代码提示。我使用的是ORD 18.2 core 27的Win10环境，可以使用Wallet CREATE创建钱包，但Wallet RECIVE无法接收。 INDEX同步也已经完成，

我也遇到了这样的问题！求解！！！！！！！！！！

**Comment by zq19** [comment]
same error, the default server url is 
![image](https://github.com/ordinals/ord/assets/50872563/4574d9e0-46ab-4613-8fdc-c806d8839c6d)
but 
![image](https://github.com/ordinals/ord/assets/50872563/a0e5f918-ca3f-47db-aa6c-725efd5a9d5f)
then i tried 127.0.0.1:80, it worked 
![image](https://github.com/ordinals/ord/assets/50872563/dddd861e-8693-4d35-8410-4ea83e2ef570)
terminal still shows listening 0.0.0.0:80, but i can visit through 127.0.0.1:80.   so i try this 
![image](https://github.com/ordinals/ord/assets/50872563/29cdf634-4806-4353-b242-67b80ad73fc3)
sadly,,,,how to solve it ? please help

**Comment by huobiteren007** [comment]
I had this problem too!

**Comment by huobiteren007** [comment]
Close VPN proxy, perfect solution to the problem
