### ISSUE TITLE
src/index/lot.rs:78:9: attempt to divide by zero

### ISSUE THREAD

**Issue by cvasqxz** [ordinals/ord#3678]
Hi, today I tried to run my ord instance and it's crashing with this stack trace

```
$ export RUST_BACKTRACE=full
$ ./ord-0.18.1/ord --index-runes server --http-port 8080
Listening on http://0.0.0.0:8080
[indexing blocks] █████████████████████████████████████████████████████████████████████░ 840357/840686
thread '<unnamed>' panicked at src/index/lot.rs:78:9:
attempt to divide by zero
stack backtrace:
   0:     0x5e420573b436 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5e420573b436 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5e420573b436 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5e420573b436 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5e420576b7c0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5e420576b7c0 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5e420573708f - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5e420573b214 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5e420573b214 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5e420573ca97 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5e420573c7f9 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5e420573cf28 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5e420573cdc9 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x5e420573b936 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5e420573cb54 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x5e4204af84f5 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x5e4204af85b3 - core::panicking::panic::h44790a89027c670f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
  17:     0x5e420507ed54 - ord::index::updater::rune_updater::RuneUpdater::index_runes::hff2233ef358081e3
  18:     0x5e4205085945 - ord::index::updater::Updater::index_block::h465dabfd3b47e549
  19:     0x5e420509319b - ord::index::Index::update::h8b53ee6418521dd1
  20:     0x5e4204ee5d05 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f63813102c2e459
  21:     0x5e4204ee90b9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h68771febae0a01d4
  22:     0x5e4205742245 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  23:     0x5e4205742245 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  24:     0x5e4205742245 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  25:     0x7805bdc94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  26:     0x7805bdd26850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  27:                0x0 - <unknown>
```

**Comment by cryptoni9n** [comment]
Hi cvasqxz, please try upgrading to v0.18.3 and retry.  Many users on the [Ordicord ](https://discord.com/invite/ordinals)have experienced this issue and have resolved it in the latest version.  Please visit us in the #tech-support channel of the [Ordicord](https://discord.com/invite/ordinals) in the future if you need further assistance.
